### ISSUE TITLE
TODO: 关于自动决战的开发

### ISSUE THREAD

**Issue by Saratoga-Official** [Saratoga-Official/MaaJR#2]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的建议未被提及

### 说说你遇到的问题？

自动决战需要考虑的东西很多，目前已经写出来开头，但后续随机性大，需要一个足够稳定的公式化打法

### 有什么好的想法？

目前我的思路是：开局抓两个4费鱼，然后用哈巴库克技能抓一个改造鱼开局
